# ==============================================================================
# Script:           beta_vae.yaml
# Purpose:          Beta-VAE training configurations
# Author:           Sophia Li
# Affiliation:      CCG Lab, Princess Margaret Cancer Center, UHN, UofT
# Date:             11/14/2025
#
# Notes:            Configurations are inspired by RNA-CDM.
# ==============================================================================

# =====| Optuna Hyperparameter Sweep |=========================================

# Path to the input training data
project_data_dir: data/training/methylation
training_data_dir: data/training/methylation

# Path to the study and experiment save directory
experiment_dir: experiments/beta_vae
checkpoint_dir: models/beta_vae

# Split Data paths
train_adata_path: "data/training/methylation/pancancer_train_adata.h5ad"
val_adata_path: "data/training/methylation/pancancer_val_adata.h5ad"
test_adata_path: "data/training/methylation/pancancer_test_adata.h5ad"

# -----| Fixed Parameters |----------------------------------------------------

# Input AnnData object dimension (number of genes)
input_dim: 225410

# Device parameters
num_workers: 2

# Max training epochs
max_epochs: 300

# Hyperparameter sweep ranges
batch_size: [32, 256]
latent_dim: [128, 512]
beta: [0.001, 0.1]
lr: [0.0001, 0.01]

# -----| Sweep Parameters |----------------------------------------------------

encoder_dims:
  - [2048, 512, 128]
  - [1024, 256, 128]
  - [2048, 1024, 256, 128]

latent_dim: [64, 128]
beta: [0.001, 0.003]
input_dropout: [0.1, 0.3]
num_cycles: [2]
lr: [0.0001, 0.002]
batch_size: [64, 128]
